import puppeteer from 'puppeteer-core';
import fs from 'fs'; import path from 'path';
import { pathToFileURL } from 'url'; import { execFileSync } from 'child_process';
const DIR='c:/!Ahn/Corporation/##. 기획/05. 매출가능사업구상/01. SNS 채널운영(AI 제작)/00. 콘텐츠 제작 자동화/02. A Creative Studio/11. 스튜디오 로고';
const HTML=path.join(DIR,'여리로고_애니메이션_정제.html');
const OUT='C:/Users/user/AppData/Local/Temp/claude/C--yubi-director-app-api-claude/5843a2bf-7e08-4aa3-acac-46ce951dde7c/scratchpad';
const CH='C:/Program Files/Google/Chrome/Application/chrome.exe';
const FF='C:/Users/user/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.1.1-full_build/bin/ffmpeg.exe';
const FPS=30, DUR=6.9, N=Math.round(FPS*DUR);
const b=await puppeteer.launch({executablePath:CH,headless:'new',args:['--no-sandbox','--force-color-profile=srgb','--font-render-hinting=none']});
const p=await b.newPage(); await p.setViewport({width:1920,height:1080,deviceScaleFactor:1});
await p.goto(pathToFileURL(HTML).href,{waitUntil:'networkidle0'});
await p.waitForFunction('window.__ready===true'); await new Promise(r=>setTimeout(r,400));
const d=OUT+'/_fr'; fs.rmSync(d,{recursive:true,force:true}); fs.mkdirSync(d);
for(let i=0;i<N;i++){ await p.evaluate(t=>window.renderFrame(t),i/FPS);
  await p.screenshot({path:path.join(d,`f${String(i).padStart(5,'0')}.png`),clip:{x:0,y:0,width:1920,height:1080}}); }
await b.close();
const O=path.join(DIR,'여리로고_오프닝_정제.mp4');
execFileSync(FF,['-y','-framerate',String(FPS),'-i',path.join(d,'f%05d.png'),'-c:v','libx264','-pix_fmt','yuv420p','-crf','18','-preset','slow','-movflags','+faststart',O],{stdio:'inherit'});
const secs=[0.6,1.3,2.0,2.6,3.2,3.6,4.0,4.4,4.9,5.4,6.0,6.6];
const md=d+'_m'; fs.rmSync(md,{recursive:true,force:true}); fs.mkdirSync(md);
secs.forEach((s,i)=>{const fr=Math.min(Math.round(s*FPS),N-1);fs.copyFileSync(path.join(d,`f${String(fr).padStart(5,'0')}.png`),path.join(md,`m${String(i).padStart(2,'0')}.png`));});
execFileSync(FF,['-y','-i',path.join(md,'m%02d.png'),'-vf','scale=470:-1,tile=4x3','-frames:v','1','-update','1',`${OUT}/_ref_mtg.png`],{stdio:'inherit'});
console.log('done');
